options {
    directory "/var/cache/bind";

    listen-on { 172.30.0.52; };
    listen-on-v6 { none; };

    recursion no;

    allow-query { any; };
};

zone "theta.signed" {
    type primary;
    file "/var/lib/bind/db.theta.signed.signed";
};
